### PR TITLE
ci: gcc: add workflows for gcc-10 with coroutines

### PR DESCRIPTION
**Pull request by williamspatrick**

### CODE REVIEW

**Comment by williamspatrick** [comment]
I'm half expecting this PR to fail due to #307 .

**Comment by ericniebler** [comment]
This PR could contain two commits: the first would work around the gcc bug by conditionally defining `UNIFEX_NO_UNIQUE_ADDRESS` as empty for gcc-10 (with coroutines?), and the second which adds the CI support.

Would also be good to find a minimal repro and file a compiler bug, and have a link to the bug in a comment.

**Comment by williamspatrick** [comment]
Marked this as draft until PR #314 is merged and GH Actions update gcc-10 to 10.3.  Will then rebase and mark for review.

**Comment by ericniebler** [comment]
> Marked this as draft until PR #314 is merged 

Done.

> and GH Actions update gcc-10 to 10.3. Will then rebase and mark for review.

Why do we need to wait for GH Actions to update gcc-10? After #314, won't it Just Work now?

**Comment by williamspatrick** [comment]
> Why do we need to wait for GH Actions to update gcc-10? After #314, won't it Just Work now?

After #314, everything passes with GCC 10.3.  With GCC 10.2, even before #314, everything compiles but does not pass unit-tests.  There were fixes that went into GCC 10.2 for coroutines (which allows the unit tests pass here).

**Comment by ericniebler** [comment]
> There were fixes that went into GCC 10.2 for coroutines (which allows the unit tests pass here).

Ah, I see. Thanks.

**Comment by williamspatrick** [comment]
> There were fixes that went into GCC 10.2 for coroutines (which allows the unit tests pass here).

I typo'd here.  GCC 10.3 has the fixes for coroutine execution.  GCC 10.2 will fail unit tests.

https://github.com/actions/virtual-environments shows the current deployment rate of Ubuntu images for the GH Action execution environment. `ubuntu20-20210628.1` is the image which upgraded GCC 10.2 -> GCC 10.3.  It is currently at a 22.28% deployment rate.  I will monitor over the next few days and once I see that image reach 100% I'll rebase/retrigger this PR to confirm the `GCC 10.3 w/Coroutines` stages pass and then this can be merged.

**Comment by ericniebler** [comment]
Thanks!

**Pull request merged**
